version: '3'
services:
  search-ui:
    build:
      context: ../
      dockerfile: ./search-ui/Dockerfile
    container_name: search-ui
    environment:
      - ELASTICSEARCH_HOST=http://es01:9200 # http://es01:9200
      - ELASTICSEARCH_API_VERSION=7
    ports:
      - "3000:3000"
    networks:
      - elastic-backend_elastic

networks:
  elastic-backend_elastic:
    external: true   # This is an existing external network from elastic backend