version: '3'
services:
  search-ui:
    build: .
    container_name: search-ui
    environment:
      - ELASTICSEARCH_HOST=http://13.214.153.0:9200 # http://es01:9200
      - ELASTICSEARCH_API_VERSION=7
    ports:
      - "3000:3000"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge